openapi: 3.0.0
info:
  title: HelloService
  description: Swagger file for generating WSDL
  version: '1.0'
servers:
- url: https://www.example.com/SayHello/
paths:
  /messages:
    get:
      tags:
      - Messages
      description: Get all message entries
      operationId: GetMessages
      responses:
        200:
          description: List of all message objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
                description: List of all message objects
                xml:
                  name: Messages
                  wrapped: true
        404:
          description: No messages found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /message:
    post:
      tags:
      - Messages
      description: Send a message
      operationId: SendMessage
      requestBody:
        description: 'Message object'
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      responses:
        200:
          description: Message id will be received if message is successfully stored.
          content:
            application/json:
              schema:
                type: string
        404:
          description: No messages found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    get:
      tags:
      - Messages
      description: View message entry
      operationId: GetMessage
      parameters:
      - name: messageId
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: Message object against the id, if found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        404:
          description: No messages found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Message:
      title: Message
      required:
      - from
      - to
      - text
      - date
      type: object
      properties:
        from:
          type: string
        to:
          type: string
        text:
          type: string
        date:
          type: string
          format: date-time
        id:
          type: string
          xml:
            name: id
            attribute: true
      xml:
        name: MessageEntry
        namespace: https://www.example.com/message
        prefix: m
    Error:
      title: Error
      required:
      - message
      type: object
      properties:
        message:
          type: string
      xml:
        name: Error
        namespace: https://www.example.com/error
        prefix: e
tags:
- name: Messages